groupName: cert-manager.webhook.transip

certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager

image:
  repository: maaroen/cert-manager-webhook-transip
  tag: latest
  privateRegistrySecretName: ""
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

# Optional DNS settings, useful if you have a public and private DNS zone for
# the same domain on Route 53. What follows is an example of ensuring
# cert-manager can access an ingress or DNS TXT records at all times.
# NOTE: This requires Kubernetes 1.10 or `CustomPodDNS` feature gate enabled for
# the cluster to work.
# podDnsPolicy: "None"
# podDnsConfig:
#   nameservers:
#     - "1.1.1.1"
#     - "8.8.8.8"

service:
  type: ClusterIP
  port: 443

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 64Mi
  # requests:
  #  cpu: 100m
  #  memory: 16Mi

nodeSelector: {}

tolerations: []

affinity: {}
